version: 2
updates:
  - package-ecosystem: cargo
    directory: "/projects/runner"
    labels:
      - dependencies
      - automerge
    schedule:
      interval: monthly
      time: "04:00"
    open-pull-requests-limit: 10
  - package-ecosystem: cargo
    directory: "/projects/cli"
    labels:
      - dependencies
      - automerge
    schedule:
      interval: monthly
      time: "04:00"
    open-pull-requests-limit: 10
  - package-ecosystem: bundler
    directory: "/projects/app"
    labels:
      - dependencies
      - automerge
    schedule:
      interval: monthly
      time: "04:00"
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/projects/app"
    schedule:
      interval: monthly
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - pepibumur
    labels:
      - dependencies
      - automerge
  - package-ecosystem: npm
    directory: "/projects/website"
    schedule:
      interval: monthly
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - pepibumur
    labels:
      - dependencies
      - automerge
  - package-ecosystem: npm
    directory: "/projects/docs"
    schedule:
      interval: monthly
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - pepibumur
    labels:
      - dependencies
      - automerge
  - package-ecosystem: bundler
    directory: "/projects/chimera"
    labels:
      - dependencies
      - automerge
    schedule:
      interval: monthly
      time: "04:00"
    open-pull-requests-limit: 10
