require:
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  DisplayStyleGuide: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 200

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/ClassAndModuleChildren:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
