# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

ruby "3.0.1"

gem "byebug", "~> 11.1"
gem "minitest", "~> 5.14"
gem "minitest-reporters", "~> 1.4"
gem "mocha", "~> 1.12"
gem "rake", "~> 13.0"
gem "rubocop", "~> 1.14"
gem "rubocop-minitest", "~> 0.12.1"
gem "rubocop-rails", "~> 2.10.1"
gem "rubocop-rails_config"
gem "thor", "~> 1.1"
gem "zeitwerk", "~> 2.4"
