[package]
name = "buildify"
version = "0.1.0"
authors = ["Pedro Piñera <pedro@ppinera.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
