# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
git_source(:github) { |repo_name| "https://gitlab.com/#{repo_name}" }

gem "byebug", "~> 11.1"
gem "zeitwerk", "~> 2.4"
gem "thor", "~> 1.1"
gem "rake", "~> 13.0"
gem "minitest", "~> 5.14"
gem "minitest-reporters", "~> 1.4"
gem "mocha", "~> 1.12"
gem "rubocop", "~> 1.11"
gem "rubocop-rails", "~> 2.9.1"
gem "rubocop-rails_config"
