# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.0.1"

# Specify your gem's dependencies in buildify.gemspec
gemspec

gem "minitest", "~> 5.0"
gem "minitest-reporters", "~> 1.4"
gem "rake", "~> 13.0"
gem "rubocop", "~> 1.7"
