name: CLI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - projects/cli/**
      - .github/workflows/cli.yml

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: --release --all-features --manifest-path projects/cli/Cargo.toml
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path projects/cli/Cargo.toml
