name: CLI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - projects/cli/**
      - .github/workflows/cli.yml

env:
  RUBY_VERSION: "3.0.1"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install dependencies
        working-directory: projects/cli
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs=4 --retry=3
      - name: Run tests
        working-directory: projects/cli
        run: |
          bundle exec rake test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install dependencies
        working-directory: projects/cli
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs=4 --retry=3
      - name: Lint Ruby
        working-directory: projects/cli
        run: |
          bundle exec rubocop
